---
- name: "Check if {{ docker_compose_project_directory_ }} directory exists"
  stat:
    path: "{{ docker_compose_project_directory_ }}"
  register: docker_compose_project_directory_stat
  when: not docker_compose_only_copy_files

- name: Run docker compose down
  shell:
    chdir: "{{ docker_compose_project_directory_ }}"
    cmd: sudo docker compose -p formula-ap1 down
  when: not docker_compose_only_copy_files and docker_compose_project_directory_stat.stat.exists

- name: Remove log volumes
  shell: "sudo docker volume rm {{ item | quote }}"
  loop:
    - formula-ap1_scraper-v0-logs
    - formula-ap1_traefik-logs
  when: not docker_compose_only_copy_files and docker_compose_project_directory_stat.stat.exists

- name: Copy compose files
  import_tasks: copy_compose_files.yml

- name: Run docker compose up
  shell:
    chdir: "{{ docker_compose_project_directory_ }}"
    cmd: sudo docker compose -p formula-ap1 up -d --pull always
  when: not docker_compose_only_copy_files
