---
- name: Generate ssh key
  block:
    - name: Create ssh directory
      file:
        path: "/home/{{ ssh_localhost_user }}/.ssh"
        state: directory
        owner: "{{ ssh_localhost_user }}"
        group: "{{ ssh_localhost_user }}"
        mode: "700"

    - name: Generate ssh key pair
      user:
        name: "{{ ssh_localhost_user }}"
        generate_ssh_key: yes
        ssh_key_type: "{{ ssh_key_type_ }}"
        ssh_key_file: ".ssh/{{ inventory_hostname }}"
        ssh_key_passphrase: "{{ ssh_key_passphrase_ }}"
      register: ssh_key

    - name: Set permissions for ssh key pair
      block:
        - name: Set permissions for private key
          file:
            path: "/home/{{ ssh_localhost_user }}/.ssh/{{ inventory_hostname }}"
            owner: "{{ ssh_localhost_user }}"
            group: "{{ ssh_localhost_user }}"
            mode: "400"

        - name: Set permissions for public key
          file:
            path: "/home/{{ ssh_localhost_user }}/.ssh/{{ inventory_hostname }}.pub"
            owner: "{{ ssh_localhost_user }}"
            group: "{{ ssh_localhost_user }}"
            mode: "644"

    - name: Set ssh config
      blockinfile:
        dest: "/home/{{ ssh_localhost_user }}/.ssh/config"
        block: "{{ lookup('template', '../templates/ssh_localhost_config.j2') }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR {{ inventory_hostname }}"
        create: true
        owner: "{{ ssh_localhost_user }}"
        group: "{{ ssh_localhost_user }}"
        mode: "600"
  delegate_to: localhost

- name: Authorize public key on the server
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ ssh_key.ssh_public_key }}"
