# Base config
# Available options: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
server:
  http2:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    web:
      pageable:
        page-parameter: pageNumber
        size-parameter: pageSize
        default-page-size: ${default-page-size:25}
        max-page-size: ${max-page-size:100}
  web:
    locale: en
    resources:
      # Needed for NoHandlerFoundException handling
      # https://stackoverflow.com/a/51050702
      add-mappings: false
  jackson:
    # Do not include empty fields in json
    default-property-inclusion: non_empty
