# https://typescript-eslint.io/linting/typed-linting
env:
  node: true
  es2022: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-type-checked"
parser: "@typescript-eslint/parser"
parserOptions:
  project: true
  tsconfigRootDir: __dirname
plugins:
  - "@typescript-eslint"
root: true
rules:
  no-unused-vars: off
  "@typescript-eslint/no-unused-vars": warn
