# Season
seasonId:
  name: seasonId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/seasonId"
seasonIdQuery:
  name: seasonId
  in: query
  required: false
  schema:
    $ref: "./schemas.yml#/seasonId"
seasonYear:
  name: seasonYear
  in: query
  schema:
    $ref: "./schemas.yml#/seasonYear"

# Race
raceId:
  name: raceId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/raceId"
raceIdQuery:
  name: raceId
  in: query
  required: false
  schema:
    $ref: "./schemas.yml#/raceId"
raceName:
  name: raceName
  in: query
  schema:
    $ref: "./schemas.yml#/raceName"
date:
  name: date
  in: query
  schema:
    $ref: "./schemas.yml#/date"

# Team
teamId:
  name: teamId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/teamId"
teamIdQuery:
  name: teamId
  in: query
  required: false
  schema:
    $ref: "./schemas.yml#/teamId"
teamName:
  name: teamName
  in: query
  schema:
    $ref: "./schemas.yml#/teamName"

# Driver
driverId:
  name: driverId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/driverId"
driverIdQuery:
  name: driverId
  in: query
  required: false
  schema:
    $ref: "./schemas.yml#/driverId"
driverIdQueryRequired:
  name: driverId
  in: query
  required: true
  schema:
    $ref: "./schemas.yml#/driverId"
driverCode:
  name: driverCode
  in: query
  schema:
    $ref: "./schemas.yml#/driverCode"

# Engine
engineId:
  name: engineId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/engineId"
manufacturer:
  name: manufacturer
  in: query
  schema:
    $ref: "./schemas.yml#/manufacturer"

# TeamOfSeason
teamOfSeasonId:
  name: teamOfSeasonId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/teamOfSeasonId"

# DriverOfRace
driverOfRaceId:
  name: driverOfRaceId
  in: path
  required: true
  schema:
    $ref: "./schemas.yml#/driverOfRaceId"
