---
- name: Disable IPv6
  copy:
    src: disable-ipv6.conf
    dest: /etc/sysctl.d/999-disable-ipv6.conf
    owner: root
    group: root
    mode: "644"
  notify: Reload procps service
  when: system_disable_ipv6 | bool
