---
- name: Start docker-resource-limit.slice
  systemd:
    daemon_reload: true
    name: docker-resource-limit.slice
    state: started
    enabled: true

- name: Restart docker
  service:
    name: docker
    state: restarted
