name: Lint OpenAPI
on:
  pull_request:
    branches: ["main"]
    paths:
      - "api/openapi/**"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint-openapi:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Use latest node version
          node-version: "*"
      - name: Install redocly cli
        run: npm install -g ${{ vars.REDOCLY_CLI }}
      - name: Lint OpenAPI
        run: redocly lint api-internal --config ${{ vars.REDOCLY_CLI_CONFIG }}
