name: Lint OpenAPI
on:
  push:
    paths:
      - "openapi/**"
  pull_request:
    branches: ["main"]
    paths:
      - "openapi/**"
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lint-openapi:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "./openapi"
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Use latest node version
          node-version: "*"
      # Install redocly cli
      - run: npm install -g ${{ vars.REDOCLY_CLI }}
        name: Install redocly cli
      - run: redocly lint --config ./redocly-cli-config.yml
        name: Lint OpenAPI
